# Generated by Django 2.1.3 on 2018-11-16 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('currentLocation', models.CharField(max_length=100)),
                ('orgTag', models.CharField(max_length=20)),
                ('manufacturer', models.CharField(max_length=30)),
                ('manufacturerPartNum', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('dateImplemented', models.DateField()),
                ('maintNotes', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Employee'),
        ),
    ]
