# Generated by Django 2.1.3 on 2018-11-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181116_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='uniqueIdentifier',
            field=models.CharField(default=213, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
